config/routes.rb
YscAlums::Application.routes.draw do

  get "users/new"

  resources :users
  match '/settings', :to => 'users#settings'
  match '/users/:id/change-settings', :to => 'users#change_settings', :as => :change_settings    # second one corresponds to actual method
  match '/users/:id/change-password', :to => 'users#change_password', :as => :change_password
  match '/users/:id/make-admin', :to => 'users#make_admin', :as => :make_admin

  match '/confirm/:confirm_code', :to => 'users#confirm_code', :as => :confirm_code
  match '/resend-confirmation', :to => 'users#resend_confirmation', :as => :resend_confirmation
  
  match '/reset-password', :to => 'users#reset_password', :as => :reset_password, :via => :get
  match '/reset-password', :to => 'users#send_reset_password_email', :via => :post

  match '/register', :to => 'users#new', :as => :register

  resources :simple_emails, :only => [:new, :create, :destroy]
  match '/users/:id/email', :to => 'simple_emails#new', :as => :send_email

  resources :sessions, :only => [:new, :create, :destroy]    # destroys session, not user
  
  match '/admin-cp/users', :to => 'users#admin_cp_users', :as => :admin_cp_users
  match '/admin-cp/emails', :to => 'simple_emails#admin_cp_emails', :as => :admin_cp_emails
  match '/admin-cp/edit-field', :to => 'users#edit_field', :as => :edit_field
  match '/admin-cp/stats', :to => 'users#admin_cp_stats', :as => :admin_cp_stats

  resources :routes, :only => [:create, :destroy]

  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy', :via => :delete

  match "/home", :to => 'static_pages#home'
  match "/about", :to => 'static_pages#about'
  match "/help", :to => 'static_pages#help'
  match "/contact", :to => 'static_pages#contact', :as => :contact, :via => :get
  match "/contact", :to => 'static_pages#send_contact_email', :via => :post
  match "/test", :to => 'static_pages#test'

  root :to => 'static_pages#home'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	
  def home
  end

  def about
  end

  def help
  end

  def contact
  end
  
  def send_contact_email
    #redirect_to(change_settings_url(current_user))
    #return
    email = params[:email_from].to_s
    if (!(email =~ /\A[\w+\-.]+@[a-zA-Z0-9_]*\.(ru|ae)\z/) && !params[:email_from].blank? && !params[:email_subject].blank? && !params[:email_message].blank?)
      flash[:success] = "Your message has been successfully delivered to the yscalumni.org admins!"
      UserMailer.email_admin_list(get_admin_email_list, params[:email_from], params[:email_subject], params[:email_message]).deliver
      redirect_to(home_url)
    else
      flash.now[:error] = "Check to make sure that none of the fields are blank!"
      render('contact')
    end
  end

  def test
    @test_string = urlsafe_randstr
    @valid_yale = true #has_valid_yale_email(current_user)
    @user = current_user
  end
  VALID_YALE_EMAIL_REGEX = /\A[\w+\-.]+@(aya\.)?yale\.edu\z/i
  def has_valid_yale_email(user)
    VALID_YALE_EMAIL_REGEX === user.email
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<%= provide(:title, "About") %>

<h1>About</h1>

<div>
  As YSC, part of our  mission statement is to be committed to resourcing and networking YSC students and alumni throughout the world.  Our website supports this by helping YSC students and alum connect with other alum.<br/><br/>
</div>

<p>We'd like to thank:</p>
<ol>
  <li><strong>Michael Hartl</strong> for making an amazing, free Ruby on Rails tutorial (which we completed 5 times).</li>
  <li><strong>Ryan Bates</strong> for his quality RailsCasts that helped us implement search by location and profile pictures.</li>
  <li><strong>Geocoder</strong>, a Rubygem that has proven to be a real gem for us.</li>
  <li><strong>Ben Robbins</strong> for putting his picture in the public domain, which we used to test image display on our website.</li>
</ol>

app/views/static_pages/contact.html.erb
<%= provide(:title, "Contact") %>

<h1 class="no-bottom-margin">Contact</h1>

<h2>
  Found a bug, want to tell us something, think we're cool?<br/>
  Send an email to the admins at yscalumni.org
</h2>

<%= form_tag(contact_url, :method => :post) do %>

  <%= label_tag :email_from, "From" %>
  <%= text_field_tag :email_from, if (params[:email_from].present?) then params[:email_from] elsif (!current_user.nil?) then current_user.email else '' end, :class => "has-focus-tooltip", :title => "The email address we're going to reply to, i.e. YOUR email address" %>

  <%= label_tag :email_subject, "Subject" %>
  <%= text_field_tag :email_subject, params[:email_subject] %>
  
  <%= label_tag :email_message, "Message" %>
  <%= text_area_tag :email_message, params[:email_message], :class => "contact-email-message" %>
  
  <%= submit_tag "Send email", :class => "btn btn-large btn-primary" %>

<% end %>

app/views/static_pages/help.html.erb
<%= provide(:title, "Help") %>

<h1>Help</h1>
<p>God is our refuge and strength,<br/>
an ever-present help in trouble.<br/>
-- Psalm 46:1</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<div class="center hero-unit">
	<h1>Welcome</h1>
	<h2>to the YSC Alumni Directory</h2>
	<% if (!signed_in?) %>
	  <p id="home-page-buttons"><%= link_to("Login", login_url, :class => "btn btn-large btn-primary") %>
	     <%= link_to("Register", register_url, :class => "btn btn-large") %></p>
	<% end %>
	<p class="home-text">Welcome to the YSC Alumni Directory.  The purpose of this website is to facilitate
	   meaningful and helpful connections among alumni and between alumni and students.  A
	   key component of YSC's mission is to send Yalies into the world who are kingdom-minded
	   and vision-driven followers of Jesus.  We hope this website will be able to contribute
	   in that direction.</p>
	<p class="home-text">If you are an alum and would like to be a resource, go ahead and fill out your profile
	   information.  The website will allow registered users to make initial contact with any
	   listed alumni users.  If and how you choose to respond is totally up to you.  In order
	   to protect your privacy, we will not list your full last name, and no one's personal contact
	   information (including email address) will be available.  If you register, you will also be
	   able to send messages to other alum.</p>
	<p class="home-text">If you are a student, just register and feel free to contact alumni, keeping in mind
     the heart behind the website.  Thanks for connecting!</p>
</div>
<a href="http://yalestudentsforchrist.org">Visit the Yale Students for Christ Website</a>

app/views/static_pages/new.html.erb
<h1>StaticPages#new</h1>
<p>Find me in app/views/static_pages/new.html.erb</p>

app/views/static_pages/settings.html.erb
<% provide(:title, 'Settings') %>

<h1>Change your settings:</h1>
<ol>
  <li><%= link_to("Edit information", edit_user_url(current_user)) %></li>
  <li><%= link_to("Edit account settings", change_settings_url(current_user)) %></li>
  <li><%= link_to("Change password", change_password_url(current_user)) %></li>
</ol>

app/views/static_pages/test.html.erb
<% provide(:title, "Testing") %>

<h1>Test page</h1>

<p>Expecting residential college below:</p>
<p><%= @user.residential_college %></p>
<p><%= @user.residential_college_abbreviation %></p>

<p>Expecting class year below:</p>
<p><%= @user.class_year %></p>
<p><%= @user.class_year_abbreviation %></p>

<p>Overall</p>
<p><%= @user.college_and_year_abbreviation %>

<p>General info</p>
<p><%= @user.display_general_info %></p>

<%= @user.abbreviated_name %>

<p>Expecting a last_visited variable</p>
<p><%= @user.last_visited %></p>