config/routes.rb
YscAlums::Application.routes.draw do

  get "users/new"

  resources :users
  match '/settings', :to => 'users#settings'
  match '/users/:id/change-settings', :to => 'users#change_settings', :as => :change_settings    # second one corresponds to actual method
  match '/users/:id/change-password', :to => 'users#change_password', :as => :change_password
  match '/users/:id/make-admin', :to => 'users#make_admin', :as => :make_admin

  match '/confirm/:confirm_code', :to => 'users#confirm_code', :as => :confirm_code
  match '/resend-confirmation', :to => 'users#resend_confirmation', :as => :resend_confirmation
  
  match '/reset-password', :to => 'users#reset_password', :as => :reset_password, :via => :get
  match '/reset-password', :to => 'users#send_reset_password_email', :via => :post

  match '/register', :to => 'users#new', :as => :register

  resources :simple_emails, :only => [:new, :create, :destroy]
  match '/users/:id/email', :to => 'simple_emails#new', :as => :send_email

  resources :sessions, :only => [:new, :create, :destroy]    # destroys session, not user
  
  match '/admin-cp/users', :to => 'users#admin_cp_users', :as => :admin_cp_users
  match '/admin-cp/emails', :to => 'simple_emails#admin_cp_emails', :as => :admin_cp_emails
  match '/admin-cp/edit-field', :to => 'users#edit_field', :as => :edit_field
  match '/admin-cp/stats', :to => 'users#admin_cp_stats', :as => :admin_cp_stats

  resources :routes, :only => [:create, :destroy]

  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy', :via => :delete

  match "/home", :to => 'static_pages#home'
  match "/about", :to => 'static_pages#about'
  match "/help", :to => 'static_pages#help'
  match "/contact", :to => 'static_pages#contact', :as => :contact, :via => :get
  match "/contact", :to => 'static_pages#send_contact_email', :via => :post
  match "/test", :to => 'static_pages#test'

  root :to => 'static_pages#home'

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  ### EVERY TIME YOU CREATE A NEW PAGE, MAKE SURE TO MODIFY THE FILTERS BELOW AS WELL!!! ###

  # The user must be signed in to view all pages *EXCEPT* the following.
  before_filter :signed_in_user, :except => [:new, :create, :destroy, :reset_password, :send_reset_password_email]
  
  # The user must NOT be signed in to view the following pages
  before_filter :not_signed_in_user, :only => [:new, :create, :reset_password, :send_reset_password_email]

  # The user must have confirmed their email to view the following pages
  before_filter :check_confirmed_user, :only => [:index, :show]

  # The user must be the correct user (or an admin) when changing settings, i.e. no modifying other people's settings of equal or higher rank!
  before_filter :correct_user, :only => [:edit, :update, :change_settings, :change_password]

  # Nobody can view student profiles except for admins
  before_filter :cant_view_students, :only => :show

  # The following actions are restricted to admins only
  before_filter :admin_user, :only => [:destroy, :make_admin, :admin_cp_users, :edit_field]

  # Remember which edit page you came from so that you can re-render it if it fails verification
  before_filter :save_edit_type, :only => [:edit, :change_settings, :change_password, :edit_field]

  # Make sure a user can't resend a confirmation email if they have already confirmed
  before_filter :dont_resend_confirmation, :only => [:resend_confirmation]

  # A class-static topics hash to be used in multiple methods
  # Forced to used ActiveSupport::OrderedHash because DreamHost uses Ruby 1.8.7 (unfortunately)
  @@topics = ActiveSupport::OrderedHash.new
  @@topics[:church_comm]    = "Church and Community"
  @@topics[:work_min]       = "Workplace Ministry"
  @@topics[:finan_stew]     = "Financial Stewardship"
  @@topics[:miss_int_dev]   = "Missions and International Development"
  @@topics[:trial_dis]      = "Trials and Disappointment"
  @@topics[:career_changes] = "Career Changes"
  @@topics[:marriage]       = "Marriage"
  @@topics[:raise_child]    = "Raising Young Children"
  @@topics[:raise_teen]     = "Parenting Teenagers"
  @@topics[:retirement]     = "Retirement"
  @@topics[:career_sel]     = "Career Selection"
  
  # A class-static topic hash for searching.
  @@search_topics = ActiveSupport::OrderedHash.new
  @@search_topics["None specified"] = :no_topic
  @@search_topics.merge!(@@topics.invert)
  
  # A class-static hash containing the residential colleges and their abbreviations
  @@res_col = ActiveSupport::OrderedHash.new
  @@res_col["None specified"] = :default_none
  @@res_col["Pierson (PC)"] = :pierson
  @@res_col["Davenport (DC)"] = :davenport
  @@res_col["Ezra Stiles (ES)"] = :ezra_stiles
  @@res_col["Morse (MC)"] = :morse
  @@res_col["Saybrook (SY)"] = :saybrook
  @@res_col["Trumbull (TC)"] = :trumbull
  @@res_col["Berkeley (BK)"] = :berkeley
  @@res_col["Silliman (SM)"] = :silliman
  @@res_col["Timothy Dwight (TD)"] = :timothy_dwight
  @@res_col["Branford (BR)"] = :branford
  @@res_col["Calhoun (CC)"] = :calhoun
  @@res_col["Jonathan Edwards (JE)"] = :jonathan_edwards
  @@res_col["Benjamin Franklin (BF)"] = :franklin
  @@res_col["Pauli Murray (MY)"] = :murray
  
  # A class-static variable for default search distance
  @@default_distance = 50
  
  # Numbers shown per page (used by them bootstrap-paginate gem)
  @@users_shown_per_page = 10

  # This index method is quite inefficient and primitive without a sophisticated full-text search (which can't be run on DreamHost)
  # So what it does it first use geocoder's "near" method to sort the users based on distance if the field is filled in
  # And then uses my primitive search method to filter and/or sort the final results, which finally gets passed to the view
  def index
    @users = User.all

    @search_topics = @@search_topics
    @sortable_fields = @@sortable_fields
    @search_by_user_type = @@search_by_user_type

    if (params[:search_location].present?)
      @users = User.near(params[:search_location], if params[:search_distance].present? then params[:search_distance] else @@default_distance end, :order => :distance)
    elsif (params[:search_distance].present?)
      @users = User.near(current_user.display_location, params[:search_distance], :order => :distance)
    end
    
    if (params[:search_type].present?)
      if (current_user.admin?)
        if (params[:search_type].to_sym == :alumni)
          # Filter out those who are students (not alums)
          @users = @users.delete_if{|u| !u.alum }
        elsif (params[:search_type].to_sym == :students)
          # Filter out those who are alums (not students)
          @users = @users.delete_if{ |u| u.alum }
        elsif (params[:search_type].to_sym == :all)
          # do nothing
        end
      else
        # Only admins are allowed to see more than alums, so filter!
        @users = @users.delete_if{|u| !u.alum }
      end
    else
      # The default is only seeing alums (even for admins)
      @users = @users.delete_if{|u| !u.alum }
    end

    if (params[:search_fields].present?)
      @users = search_users_for(@users, params[:search_fields], true, !params[:search_location].present?)
    end

    if (params[:find_topic].present? && params[:find_topic].to_sym != :no_topic)
      @users = filter_by_topic(@users, @@topics[params[:find_topic].to_sym])
    end

    if (params[:sort_by].present? && params[:sort_by].to_sym != :default)
      if @sortable_fields.values.include?(params[:sort_by].to_sym)
        @users = sort_users_by(@users, params[:sort_by].to_sym)
      else
        flash.now[:error] = "You can't sort by that field!  Nice try, though =P"
      end
    end
    
    if (params.has_key?(:reverse))
        @users.reverse!
    end

    @users = @users.paginate(:page => params[:page], :per_page => @@users_shown_per_page)
  end

  def edit
    @user = User.find(params[:id])
    @topic_hash = @@topics
    @res_col = @@res_col
  end

  def change_settings
  	@user = User.find(params[:id])
  end

  def change_password
  	@user = User.find(params[:id])
  end

  def settings
  end

  # This method has lots of logic!  But it assumes that it's impossible for any user to guess his own or another user's confirmation code
  def confirm_code
    @code = params[:confirm_code]
    @user = User.find_by_confirmation_code(params[:confirm_code])
    if (@user.nil?)
      if (current_user.admin?)      # Admin came too late or got it wrong
        flash[:error] = "This account has most likely been confirmed already (unless you manually typed the link incorrectly)."
        redirect_to(current_user)
      else
        if confirmed_user?          # User has already confirmed himself
          flash[:info] = "Your account has already confirmed, so it doesn't have to be confirmed again =)"
          redirect_to(current_user)
        elsif                       # User got the confirmation code wrong
          flash[:error] = "You have the wrong confirmation code... check your email or get a new code!"
          redirect_to(settings_url)
        end
      end
    else                            # Account will be confirmed
      flash.now[:success] = "This account has been confirmed."
      @user.confirmation_code = nil
      @user.save(:validate => false)
      if (@user == current_user)    # Don't sign an admin into user
        sign_in(@user)
      end
    end
  end
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  # Now this checks if you need auth'ation or validation -- see private methods
  def update
    @user = User.find(params[:id])

    set_user_validations
	if params[:user][:email] =~ VALID_EMAIL_REGEX
	  @user.should_validate_email = false
	end

	
    if should_update_topics
      update_topics
    end

    if ((!should_auth || @user.authenticate(params[:old_password])) && @user.update_attributes(params[:user]))
      flash[:success] = "Information/settings have been updated successfully!"
      sign_in(@user) if (current_user?(@user))    # only sign in again if you are the current user, since admins can now change other people's settings!
      if (super_edit?)
        redirect_to(admin_cp_users_url)
      else
        redirect_to(@user)
      end
    else
      flash_appropriate_error_messages
      render(session[:edit_loc])
    end
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Thanks for signing up!  Please take a moment to update your information."
      sign_in(@user)
      send_conditional_confirmation_email
      redirect_to(edit_user_url(@user))
    else
      render('new')
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "The user has been deleted."
    redirect_to(users_url)
  end
  
  def make_admin
    @user = User.find(params[:id])
    @user.admin = true
    @user.save(:validate => false)
    flash[:success] = "You've just added a new admin!"
    redirect_to(@user)
  end

  def resend_confirmation
    @user = current_user
    send_conditional_confirmation_email
  end
  
  def reset_password
  end
  
  def send_reset_password_email
    @user = User.find_by_email(params[:email])
    if @user.nil?
      flash.now[:error] = "Sorry, we couldn't find your email in our database."
    else
      new_password = password_randstr
      @user.password = @user.password_confirmation = new_password
      @user.save(:validate => false)
      send_reset_password_email_to(@user, new_password)
      flash.now[:success] = "An email with your new password has been sent to #{@user.email}"
    end
    render('reset_password')
  end
  
  def admin_cp_users
    @users = User.all
    @attrs = User.admin_cp_attributes
    @meths = User.admin_cp_methods
    if (params[:sort_by].present? && params[:sort_by].to_sym != :default)

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_admin_cp_user.html.erb
<%= if make_link then link_to(m, edit_field_url(:user => user.id, :field => m)) else m end %> => <%= user.send(m) %><br/>

app/views/users/_user_error_messages.html.erb
<% errors = @user.filtered_error_messages %>
<% if errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(errors.count, "error") %>.
    </div>
    <ul>
    <% errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_user_in_list.html.erb
<div class="profile-pic-box">
  <%= link_to(user.profile_pic_image_tag(:search_size, "profile-pic-display"), user) %>
</div>
<div class="info-row-box">
  <div class="info-row"><%= link_to(user.abbreviated_name, user, :class => "display-name") %></div>
  <div class="info-row"><%= user.display_general_info %></div>
  <div class="info-row"><%= user.display_location %></div>
  <div class="info-row"><%= user.title %></div>
</div>

app/views/users/_user_password.html.erb
<%= f.label :password %>
<%= f.password_field :password, :class => "has-focus-tooltip", :title => "At least 6 characters long." %>

<%= f.label :password_confirmation, "Password Confirmation" %>
<%= f.password_field :password_confirmation %>

app/views/users/admin_cp_users.html.erb
<% provide(:title, "All Users") %>

<h1 class="no-bottom-margin">All Users</h1>
<h2>Admin Control Panel</h2>

<div class="topic-info">
      
    <h3>Sort / Filter Results</h3>
    
    <%= form_tag admin_cp_users_url, :method => :get do %>

        <%= select_tag(:sort_by, options_for_select([:default] + @attrs + @meths, params[:sort_by]), :class => "normal-field normal-dropdown-menu") %>
        
        <div class="check-box-with-text">
            <%= check_box_tag :reverse, '', params[:reverse], :class => "cb" %>
            <%= label_tag :reverse, 'Reverse', :class => "lbl" %>
        </div>
        
        <%= submit_tag "Sort / Filter", :name => nil %>
          
    <% end %>
    
</div>



<h3>List of all registered users</h3>
<% @users.each do |user| %>
    <div class="admin-cp-item">
        <h4><%= link_to(user.name, user) %></h4>
        <% @attrs.each do |attr| %>
            <%= render('admin_cp_user', :user => user, :m => attr, :make_link => true) %>
        <% end %>
        <% @meths.each do |meth| %>
            <%= render('admin_cp_user', :user => user, :m => meth, :make_link => false) %>
        <% end %>
    </div>
<% end %>

app/views/users/change_password.html.erb
<% provide(:title, 'Change Password') %>

<h1>Change Password</h1>

<div class="row">
	<div class="span6 offset3">
	
		<%= form_for(@user) do |f| %>
	  	<%= render 'user_error_messages' %>
	  	
			<%= label_tag :old_password %>
			<%= password_field_tag :old_password %>

			<%= render('user_password', :f => f) %>

			<%= f.submit "Save Changes", :class => "btn btn-large btn-primary" %>

		<% end %>
		
	</div>
</div>

app/views/users/confirm_code.html.erb
<% provide(:title, 'Confirm Email') %>

<h1>Confirmation successful!</h1>
<p>Thanks for confirming!  Now this account has full access to the site!</p>

app/views/users/edit.html.erb
<% provide(:title, 'Update') %>

<h1>Update User Info</h1>

<div class="row">
	<div class="span6 offset3">

    <%= render('user_error_messages') %>

		<%= form_for(@user, :html => { :multipart => true }) do |f| %>

		  <div class="topic-info">

		    <h4>Profile Picture</h4>

		    <p><%= @user.profile_pic_image_tag(:search_size, 'profile-pic-thumbnail') %></p>

		    <%= f.file_field :profile_pic, :class => "has-hover-tooltip", :title => "Please upload an actual image that is portrait-style.  Otherwise it may not display properly!" %>

		  </div>

      <div class="topic-info">

        <h4>General Info</h4>

        <%= f.label :class_year %>
        <%= f.text_field :class_year, :class => "has-focus-tooltip", :title => "Four digit year" %>
        
        <%= f.label :residential_college %>
        <p><%= f.select :residential_college, options_for_select(@res_col, @user.residential_college), {}, { :class => "normal-field normal-dropdown-menu" } %></p>

        <%= f.label :major, "Major(s)" %>
        <%= f.text_field :major, :class => "has-focus-tooltip", :title => "For searching's sake, please don't abbreviate =)" %>

        <%= f.label :title, "Occupation"  %>
        <%= f.text_field :title, :class => "has-focus-tooltip", :title => "That which occupies most of my time." %>

        <%= f.label :description, "More About You" %>
        <%= f.text_area :description, :rows => 5 %>

      </div>



	  	<div class="topic-info">

        <h4>Location Info</h4>

			  <%= f.label :city %>
			  <%= f.text_field :city, :class => "has-focus-tooltip", :title => "You must have a city in order to be searchable by location." %>

	  		<%= f.label :state, 'State / Province' %>
		  	<%= f.text_field :state %>

		 	  <%= f.label :country %>
			  <%= f.text_field :country %>

      </div>



	<div class="topic-info">

        <h4><br/>I'd be willing to talk with students and other alum about:</h4>

		  	<% @topics = @user.topics %>

        <% @topic_hash.each_pair do |k, v| %> 

          <div class="check-box-with-text">
		  	  <%= check_box_tag :"#{k.to_s}", v, !(@topics.find_by_content(v).nil?), :class => "cb" %>
	  		  <%= label_tag :"#{k.to_s}", v, :class => "lbl" %>
	  	  </div>

        <% end %>
        
        <div class="check-box-with-text">
            <%= check_box_tag :other_cb, '', !(@user.other_topic.blank?), :class => "cb" %>
            <%= label_tag :other_cb, 'Other:', :class => "lbl" %>
        </div>

        <%= f.text_field :other_topic %>

      </div>

			<%= f.submit "Save changes", :class => "btn btn-large btn-primary" %>

		<% end %>
		
	</div>
</div>

app/views/users/edit_field.html.erb
<% provide(:title, "Edit Field") %>

<h1>Edit Field<h1>
<h2>Admin Control Panel</h2>

<h4><%= @user.name %></h4>

<%= form_for(@user) do |f| %>
    <%= f.label(@field) %>
    <%= f.text_area(@field, :rows => 5) %>
    <%= f.submit("Save changes", :class => "btn btn-large btn-primary") %>
<% end %>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>

<h1>People</h1>
  
<a id="toggler" href="#" data-toggle="collapse" class="active" data-target="#search">
  <h3>Search for people</h3>
</a>

<% # Start the search options collapsed if it is the first time visiting the page, i.e. no search parameters present %>

<% if (params[:search_distance].present? || params[:search_location].present? || params[:search_fields].present? || params[:sort_by].present? || params[:search_type].present?) %>
  <div id="search" class="topic-info collapse in">
<% else %>
  <div id="search" class="topic-info collapse">
<% end %>

  <%= form_tag users_url, :method => :get do %>

      <div class="topic-info">

        <h4>Search by distance</h4>

        <%= label_tag :search_distance, "Search within" %>
        <%= text_field_tag :search_distance, params[:search_distance], :class => "narrow-field has-focus-tooltip", :title => "Default is 50 miles." %>

        <%= label_tag :search_location, "miles of" %>
        <%= text_field_tag :search_location, params[:search_location], :class => "normal-field has-focus-tooltip", :title => "Enter a city, address, or place (like Beijing University).  Default is your location if blank." %>

      </div>

      <div class="topic-info">

        <h4>Search by keyword</h4>

        <%= label_tag :search_fields, 'Search user fields' %>
        <%= text_field_tag :search_fields, params[:search_fields], :class => "normal-field has-focus-tooltip", :title => "Searches all fields (including residential college, location, etc.).  For best results, use minimal punctuation, and avoid use of 'useless' words like 'a', 'an', 'the', etc." %>

      </div>

      <div class="topic-info">

        <h4>Sort by</h4>
        <p><%= select_tag(:sort_by, options_for_select(@sortable_fields, params[:sort_by]), :class => "normal-field normal-dropdown-menu") %></p>

        <% if (current_user.admin?) %>
            <p><%= select_tag(:search_type, options_for_select(@search_by_user_type, params[:search_type]), :class => "normal-field normal-dropdown-menu") %></p>
        <% end %>
        
        <div class="check-box-with-text">
            <%= check_box_tag :reverse, '', params[:reverse], :class => "cb" %>
            <%= label_tag :reverse, 'Reverse', :class => "lbl" %>
        </div>

      </div>

      <div class="topic-info">
        <h4>Search by topic</h4>
        <p><%= select_tag(:find_topic, options_for_select(@search_topics, params[:find_topic]), :class => "normal-field normal-dropdown-menu") %></p>
      </div>

      <%= submit_tag "Search", :name => nil %>

  <% end %>

</div>

<% if @users.count == 0 %>

  Sorry... no results could be found.  Please modify your search.  Note that searching fields for very undescriptive values can result in unexpected behavior (i.e. no found results).

<% else %>

  <%= will_paginate %>
	  <div class="container users-table">
		  <% @users.each do |user| %>
		    <div class="container user-row">
			    <%= render('user_in_list', :user => user) %>
			  </div>
		  <% end %>
	  </div>
  <%= will_paginate %>
  
<% end %>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>

<h1>Registration</h1>

<div class="row">
	<div class="span6 offset3">

		<%= form_for(@user) do |f| %>

		  <%= render 'user_error_messages' %>
		  
      <div class="topic-info">

			  <h4>Please enter your basic information here.</h4>

			  <%= f.label :name %>
			  <%= f.text_field :name, :class => "has-focus-tooltip", :title => "First and last (and maybe middle)" %>

			  <%= f.label :email, 'Email' %>
			  <%= f.text_field :email, :class => "has-focus-tooltip", :title => "You need an '@yale.edu' or an '@aya.yale.edu' email in order to register.  If you don't have one, please contact Charmain directly, or reach out to the admins using the Contact page." %>

        <%= render('user_password', :f => f) %>

			  <div class="check-box-with-text">
				  <%= f.check_box :alum, :class => "cb" %>
				  <%= f.label :alum, "I'm a Yale alum!", :class => "lbl" %>
			  </div>

      </div>

			<%= f.submit "Create my account", :class => "btn btn-large btn-primary" %>

		<% end %>

		<p>Already have an account?  Click <%= link_to("here", login_url) %> to login.</p>
		
	</div>
</div>

app/views/users/reset_password.html.erb
<% provide(:title, 'Reset Password') %>

<h1>Reset Password</h1>

<div class="row">
	<div class="span6 offset3">

		<%= form_tag(reset_password_url, :method => :post) do %>

			<%= label_tag :email  %>
		  <%= text_field_tag :email, params[:email], :class => "has-focus-tooltip", :title => "Input the email you signed up with, and we'll email you a new password." %>

			<%= submit_tag "Reset my password", :class => "btn btn-large btn-primary" %>

		<% end %>

	</div>
</div>

app/views/users/settings.html.erb
<% provide(:title, 'Settings') %>

<h1>Change your settings:</h1>
<ol>
  <li><%= link_to("Edit information (intended for alumni)", edit_user_url(current_user)) %></li>
  <li><%= link_to("Edit account settings", change_settings_url(current_user)) %></li>
  <li><%= link_to("Change password", change_password_url(current_user)) %></li>
  <% if !confirmed_user? %>
    <li> <%= link_to("Resend confirmation email", resend_confirmation_url) %> </li>
  <% end %>
</ol>

app/views/users/show.html.erb
<% provide(:title, "#{@user.abbreviated_name}"'s profile') %>

<h1 class="no-bottom-margin"><%= @user.abbreviated_name %></h1>

<h2><%= @user.college_and_year_abbreviation %></h2>

<%= @user.profile_pic_image_tag(:show_size, 'profile-pic-large profile-pic-right') %>

<% if (!@user.major.blank?) || (!@user.class_year.blank?) %>

  <div class="topic-info">
  
    <h3>General Info</h3>
    
    <% if (!@user.title.blank?) %>
      <strong>Occupation:</strong> <%= @user.title %></br>
    <% end %>
    
    <% if (!@user.major.blank?) %>
      <strong>Major:</strong> <%= @user.major %></br>
    <% end %>
    
  </div>

<% end %>

<% if (!@user.city.blank?) || (!@user.state.blank?) || (!@user.country.blank?) %>

  <div class="topic-info">

    <h3>Location</h3>
    
    <% if (!@user.city.blank?) %>
      <strong>City:</strong> <%= @user.city %></br>
    <% end %>
    
    <% if (!@user.state.blank?) %>
      <strong>State:</strong> <%= @user.state %></br>
    <% end %>
    
    <% if (!@user.country.blank?) %>
      <strong>Country:</strong> <%= @user.country %></br>
    <% end %>
    
  </div>

<% end %>

<% if (!@user.topics.blank?) || (!@user.other_topic.blank?) %>

  <div class="topic-info">

    <h3>I'd be willing to talk with students about:</h3>
    <ol>
	    <%= render(@user.topics) %>
	    <% if (!@user.other_topic.blank?) %>
	      <li><%= @user.other_topic %></li>
	    <% end %>
    </ol>
    
  </div>

<% end %>

<% if (!@user.description.blank?) %>

  <div class="topic-info">

    <h3>About</h3>
    <div class="justified-text"><%= @user.description %></div>

  </div>
<% end %>

<div class="topic-info">
  <h3>Email</h3>
  <p><%= link_to("Send #{@user.abbreviated_name} an email", send_email_url(@user)) %></p>
</div>

<% if (current_user.admin? && !@user.admin?) %>
  
  <div class="topic-info">
    
    <h3>Admin Options</h3>
    <ol class="admin-option-list">
      <li><%= link_to("Delete", @user, :method => :delete, :class => "admin-option", :data => { :confirm => "Are you sure you want to delete #{@user.name}?\nYou can't undo this, and they will be deleted forever!" }) %></li>
      <li><%= link_to("Make admin", make_admin_url(@user), :class => "admin-option", :data => { :confirm => "Are you sure you want to make #{@user.name} an admin?\nIt's not that easy to un-admin/delete an admin!" }) %></li>
      <% if (!@user.confirmation_code.nil?) %>
        <li><%= link_to("Confirm", confirm_code_url(@user.confirmation_code), :class => "admin-option", :data => { :confirm => "Are you sure you want to confirm #{@user.name}?" }) %></li>
      <% end %>
      <li><%= link_to("Edit", edit_user_url(@user), :class => "admin-option") %></li>
      <li><%= link_to("Change account settings", change_settings_url(@user), :class => "admin-option") %></li>
      <li><%= link_to("Change password", change_password_url(@user), :class => "admin-option", :data => { :confirm => "Even though you're an admin, are you really sure you want to change #{@user.name}'s password?" }) %></li>
    </ol>
  </div>
<% end %>