config/routes.rb
YscAlums::Application.routes.draw do

  get "users/new"

  resources :users
  match '/settings', :to => 'users#settings'
  match '/users/:id/change-settings', :to => 'users#change_settings', :as => :change_settings    # second one corresponds to actual method
  match '/users/:id/change-password', :to => 'users#change_password', :as => :change_password
  match '/users/:id/make-admin', :to => 'users#make_admin', :as => :make_admin

  match '/confirm/:confirm_code', :to => 'users#confirm_code', :as => :confirm_code
  match '/resend-confirmation', :to => 'users#resend_confirmation', :as => :resend_confirmation
  
  match '/reset-password', :to => 'users#reset_password', :as => :reset_password, :via => :get
  match '/reset-password', :to => 'users#send_reset_password_email', :via => :post

  match '/register', :to => 'users#new', :as => :register

  resources :simple_emails, :only => [:new, :create, :destroy]
  match '/users/:id/email', :to => 'simple_emails#new', :as => :send_email

  resources :sessions, :only => [:new, :create, :destroy]    # destroys session, not user
  
  match '/admin-cp/users', :to => 'users#admin_cp_users', :as => :admin_cp_users
  match '/admin-cp/emails', :to => 'simple_emails#admin_cp_emails', :as => :admin_cp_emails
  match '/admin-cp/edit-field', :to => 'users#edit_field', :as => :edit_field
  match '/admin-cp/stats', :to => 'users#admin_cp_stats', :as => :admin_cp_stats

  resources :routes, :only => [:create, :destroy]

  match '/login', :to => 'sessions#new'
  match '/logout', :to => 'sessions#destroy', :via => :delete

  match "/home", :to => 'static_pages#home'
  match "/about", :to => 'static_pages#about'
  match "/help", :to => 'static_pages#help'
  match "/contact", :to => 'static_pages#contact', :as => :contact, :via => :get
  match "/contact", :to => 'static_pages#send_contact_email', :via => :post
  match "/test", :to => 'static_pages#test'

  root :to => 'static_pages#home'

end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <nav>
      <ul class="nav pull-right">
        <li><%= link_to("Contact", contact_url) %></li>
        <li><%= link_to("About", about_url) %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner ysc-blue-bg">
	  <div class="container">
      <nav>
        <%= link_to(image_tag("ysc-alums-banner.png", :id => "logo"), home_url) %>
	      <ul id="header-options" class="nav pull-right">
	        <li><%= link_to("Home", home_url) %></li>
	        <li><%= link_to("Help", help_url) %></li>
	        
	        <% if (signed_in?) %>
	          <li><%= link_to("People", users_url) %></li>
	          
  	        <% if (current_user.admin?) %>
              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Admin <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to("All Users", admin_cp_users_url) %></li>
                  <li><%= link_to("All Emails", admin_cp_emails_url) %></li>
                  <li><%= link_to("Stats", admin_cp_stats_url) %></li>
                </ul>
              </li>
            <% end %>
            
	        <li id="fat-menu" class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	            Account <b class="caret"></b>
	          </a>
            <ul class="dropdown-menu">
              <li><%= link_to("Profile", current_user) %></li>
              <li><%= link_to("Settings", settings_url) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to("Logout", logout_path, :method => "delete") %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to("Login", login_url) %></li>
        <% end %>
        </ul>
	    </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YSC Alumni | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= favicon_link_tag("ysc-logo-icon.png") %>
  <%= csrf_meta_tags %>
</head>
<body>

	<%= render('layouts/header') %>

	<div class="container">

		<% flash.each do |key, value| %>
			<div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>

		<%= yield %>
		
	</div>

	<%= render('layouts/footer') %>
  
</body>
</html>